import fs from "node:fs/promises";
import path from "node:path";
import { Workbook, SpreadsheetFile } from "@oai/artifact-tool";

const root = process.cwd();
const readCsv = async name => {
  const [head, ...lines] = (await fs.readFile(path.join(root, "data", "processed", name), "utf8")).trim().split(/\r?\n/);
  const headers = head.split(",");
  return lines.map(line => Object.fromEntries(headers.map((h, i) => [h, line.split(",")[i] ?? ""])));
};
const metric = JSON.parse(await fs.readFile(path.join(root, "data", "processed", "project_metrics.json"), "utf8"));
const months = await readCsv("monthly_performance.csv");
const states = await readCsv("state_performance.csv");
const segments = (await readCsv("priority_segments.csv")).slice(0, 3);
const quality = await readCsv("data_quality_checks.csv");
const num = (v) => Number(v);
const wb = Workbook.create();
const dashboard = wb.worksheets.add("Dashboard"), metrics = wb.worksheets.add("Metrics"), trend = wb.worksheets.add("Monthly trend"), state = wb.worksheets.add("State performance"), category = wb.worksheets.add("Category performance"), seller = wb.worksheets.add("Seller performance"), qualitySheet = wb.worksheets.add("Data quality"), method = wb.worksheets.add("Methodology");
const sheets = [dashboard, metrics, trend, state, category, seller, qualitySheet, method];
for (const s of sheets) { s.showGridLines = false; }
const title = (s, t) => { s.getRange("A2:H2").merge(); s.getRange("A2").values=[[t]]; s.getRange("A2").format={font:{name:"Arial",size:16,bold:true,color:"#1F2937"}}; };
const head = (s, r) => { s.getRange(r).format={fill:"#1F4E78",font:{name:"Arial",size:10,bold:true,color:"#FFFFFF"},horizontalAlignment:"center",verticalAlignment:"center",borders:{preset:"all",style:"thin",color:"#FFFFFF"}}; };
const table = (s, r) => { s.getRange(r).format={font:{name:"Arial",size:10,color:"#1F2937"},verticalAlignment:"center",borders:{preset:"outside",style:"thin",color:"#D1D5DB"}}; };
const setWidths = (s) => { s.getUsedRange().format.autofitColumns(); };

title(metrics, "Operations Metrics");
metrics.getRange("A4:B13").values = [["Metric", "Value"], ["Total orders", metric.total_orders], ["Delivered orders", metric.delivered_orders], ["Cancelled orders", metric.cancelled_orders], ["Cancellation rate", metric.cancellation_rate], ["On-time delivery rate", metric.on_time_delivery_rate], ["SLA breach rate", metric.sla_breach_rate], ["Average delivery days", metric.avg_delivery_days], ["Freight cost / delivered order (BRL)", metric.freight_cost_per_delivered_order_brl], ["On-time average review score", metric.on_time_avg_review]];
head(metrics,"A4:B4"); table(metrics,"A5:B13"); metrics.getRange("B8:B10").format.numberFormat="0.0%"; metrics.getRange("B11:B11").format.numberFormat="0.0 \"days\""; metrics.getRange("B12:B12").format.numberFormat="R$ #,##0.00"; metrics.getRange("B13:B13").format.numberFormat="0.00";

title(dashboard, "Olist Delivery Operations Performance");
dashboard.getRange("A4:L4").merge(); dashboard.getRange("A4").values=[["Real, anonymized Olist public data | Brazil | Sep 2016–Oct 2018 | Delivered-order denominator for delivery KPIs"]]; dashboard.getRange("A4").format={font:{name:"Arial",size:10,italic:true,color:"#4B5563"}};
const cards = [["Total orders","=Metrics!B5","#,##0"],["On-time delivery","=Metrics!B9","0.0%"],["Average delivery time","=Metrics!B11","0.0 \"days\""],["SLA breach rate","=Metrics!B10","0.0%"],["Cancellation rate","=Metrics!B8","0.0%"],["Freight cost / delivered order","=Metrics!B12","R$ #,##0.00"]];
cards.forEach((c,i)=>{ const col=i*2; dashboard.getRangeByIndexes(5,col,1,2).merge(); dashboard.getRangeByIndexes(6,col,1,2).merge(); dashboard.getCell(5,col).values=[[c[0]]]; dashboard.getCell(6,col).formulas=[[c[1]]]; dashboard.getRangeByIndexes(5,col,1,2).format={fill:"#DCE6F1",font:{name:"Arial",size:10,bold:true,color:"#1F4E78"},horizontalAlignment:"center"}; dashboard.getRangeByIndexes(6,col,1,2).format={fill:"#F8FAFC",font:{name:"Arial",size:14,bold:true,color:"#1F2937"},horizontalAlignment:"center",numberFormat:c[2],borders:{preset:"outside",style:"thin",color:"#B8C6D9"}}; });
dashboard.getRange("A10:E10").values=[["Priority segment","Delivered orders","Late orders","Excess late orders vs baseline","Recommended validation"]]; head(dashboard,"A10:E10");
const actions = segments.map((s, i) => [ `${s.segment_type}: ${s.segment}`, Math.round(num(s.delivered_orders)), Math.round(num(s.late_orders)), Math.round(num(s.excess_late_orders_vs_baseline)), i===0 ? "Review carrier coverage and promised-date logic" : i===1 ? "Compare routes and seller mix with the overall baseline" : "Review delivery handoff and freight conditions" ]);
dashboard.getRange("A11:E13").values=actions; table(dashboard,"A11:E13"); dashboard.getRange("A11:E13").format.wrapText=true; dashboard.getRange("A11:E13").format.rowHeight=32;
dashboard.getRange("G10:H10").merge(); dashboard.getRange("G10").values=[["Customer-impact signal"]]; head(dashboard,"G10:H10"); dashboard.getRange("G11:H13").values=[["On-time review score", metric.on_time_avg_review],["Late-delivery review score", metric.late_avg_review],["Observed gap", metric.on_time_avg_review - metric.late_avg_review]]; table(dashboard,"G11:H13"); dashboard.getRange("H11:H13").format.numberFormat="0.00";
dashboard.getRange("S1:T28").values=[["Month","On-time rate"], ...months.map(r=>[r.purchase_month, num(r.on_time_delivery_pct)])]; const line=dashboard.charts.add("line",dashboard.getRange("S1:T28")); line.title="On-time delivery trend"; line.hasLegend=false; line.setPosition("G16","N31"); line.yAxis={numberFormatCode:"0%",numberFormatSourceLinked:false};
dashboard.getRange("S30:T38").values=[["State","SLA breach rate"], ...states.slice(0,8).map(r=>[r.customer_state,num(r.sla_breach_pct)])]; const bar=dashboard.charts.add("bar",dashboard.getRange("S30:T38")); bar.title="States with highest SLA breach rate"; bar.hasLegend=false; bar.setPosition("A16","F31"); bar.yAxis={numberFormatCode:"0%",numberFormatSourceLinked:false};

const populateSummary = async (sheet, name, file, label) => { const rows=await readCsv(file); title(sheet,name); const headers=[label,"Total orders","Delivered orders","Cancelled orders","On-time delivery","SLA breach rate","Avg delivery days","Freight / delivered order (BRL)","Avg review score"]; sheet.getRange("A4:I4").values=[headers]; head(sheet,"A4:I4"); const vals=rows.map(r=>[r[label],num(r.total_orders),num(r.delivered_orders),num(r.cancelled_orders),num(r.on_time_delivery_pct),num(r.sla_breach_pct),num(r.avg_delivery_days),num(r.freight_cost_per_delivered_order_brl),num(r.avg_review_score)]); sheet.getRangeByIndexes(4,0,vals.length,9).values=vals; table(sheet,`A5:I${4+vals.length}`); sheet.getRange(`B5:D${4+vals.length}`).format.numberFormat="# ,##0"; sheet.getRange(`E5:F${4+vals.length}`).format.numberFormat="0.0%"; sheet.getRange(`G5:G${4+vals.length}`).format.numberFormat="0.0"; sheet.getRange(`H5:H${4+vals.length}`).format.numberFormat="R$ #,##0.00"; sheet.getRange(`I5:I${4+vals.length}`).format.numberFormat="0.00"; sheet.freezePanes.freezeRows(4); };
await populateSummary(state,"Customer State Performance","state_performance.csv","customer_state");
await populateSummary(category,"Category Performance","category_performance.csv","category");
title(seller,"Seller Performance (minimum 50 delivered seller-item rows)"); const sellerRows=await readCsv("seller_performance.csv"); seller.getRange("A4:H4").values=[["Seller ID","Total seller-item rows","Delivered seller-item rows","Cancellation rate","On-time delivery","SLA breach rate","Avg delivery days","Freight / delivered order (BRL)"]]; head(seller,"A4:H4"); seller.getRangeByIndexes(4,0,sellerRows.length,8).values=sellerRows.map(r=>[r.seller_id,num(r.total_orders),num(r.delivered_orders),num(r.cancelled_orders)/num(r.total_orders),num(r.on_time_delivery_pct),num(r.sla_breach_pct),num(r.avg_delivery_days),num(r.freight_cost_per_delivered_order_brl)]); table(seller,`A5:H${4+sellerRows.length}`); seller.getRange(`D5:F${4+sellerRows.length}`).format.numberFormat="0.0%"; seller.getRange(`G5:G${4+sellerRows.length}`).format.numberFormat="0.0"; seller.getRange(`H5:H${4+sellerRows.length}`).format.numberFormat="R$ #,##0.00"; seller.freezePanes.freezeRows(4);
title(trend,"Monthly Delivery Performance"); trend.getRange("A4:H4").values=[["Month","Total orders","Delivered orders","Cancelled orders","On-time delivery","SLA breach rate","Avg delivery days","Freight / delivered order (BRL)"]]; head(trend,"A4:H4"); trend.getRangeByIndexes(4,0,months.length,8).values=months.map(r=>[r.purchase_month,num(r.total_orders),num(r.delivered_orders),num(r.cancelled_orders),num(r.on_time_delivery_pct),num(r.sla_breach_pct),num(r.avg_delivery_days),num(r.freight_cost_per_delivered_order_brl)]); table(trend,`A5:H${4+months.length}`); trend.getRange(`E5:F${4+months.length}`).format.numberFormat="0.0%"; trend.getRange(`G5:G${4+months.length}`).format.numberFormat="0.0"; trend.getRange(`H5:H${4+months.length}`).format.numberFormat="R$ #,##0.00";
title(qualitySheet,"Data Quality Checks"); qualitySheet.getRange("A4:B8").values=[["Check","Issue count"],...quality.map(r=>[r.check,num(r.result)])]; head(qualitySheet,"A4:B4"); table(qualitySheet,"A5:B8");
title(method,"Methodology and Definitions"); method.getRange("A4:B12").values=[["Topic","Definition"],["Source","Olist Brazilian E-Commerce Public Dataset (real, anonymized commercial data)."],["Grain","Fact Orders has one row per order. Seller delivery fact has one row per seller-item contribution."],["On-time delivery","Delivered on or before the estimated delivery date ÷ delivered orders."],["SLA breach","Delivered after the estimated delivery date."],["Freight cost proxy","Freight value ÷ delivered orders. It is not full fulfillment cost."],["Priority segments","State/category segments ranked by excess late orders versus the overall late-delivery rate. Segments overlap and are associations, not causal claims."],["Validation","Validate route, carrier, seller, and inventory conditions before actioning a segment."],["Source URL","https://www.kaggle.com/datasets/olistbr/brazilian-ecommerce"]]; head(method,"A4:B4"); table(method,"A5:B12"); method.getRange("B5:B12").format.wrapText=true; method.getRange("B5:B12").format.columnWidth=75; method.getRange("A5:A12").format.columnWidth=22;
for (const s of sheets) setWidths(s); dashboard.getRange("A1:N31").format.columnWidth=15; dashboard.getRange("A1:A31").format.columnWidth=24; dashboard.getRange("B1:B31").format.columnWidth=19; dashboard.getRange("C1:C31").format.columnWidth=17; dashboard.getRange("D1:D31").format.columnWidth=24; dashboard.getRange("E1:E31").format.columnWidth=32;
wb.recalculate();
const preview=await wb.render({sheetName:"Dashboard",range:"A1:N31",scale:1.2,format:"png"}); await fs.writeFile(path.join(root,"images","olist_dashboard_preview.png"),new Uint8Array(await preview.arrayBuffer()));
const xlsx=await SpreadsheetFile.exportXlsx(wb); await xlsx.save(path.join(root,"excel","operations_review.xlsx"));
