table 'Vendor Performance'

	column vendor
		dataType: string
		summarizeBy: none
		sourceColumn: vendor
		annotation SummarizationSetBy = Automatic

	column total_orders
		dataType: int64
		summarizeBy: sum
		sourceColumn: total_orders
		annotation SummarizationSetBy = Automatic

	column delivered_orders
		dataType: int64
		summarizeBy: sum
		sourceColumn: delivered_orders
		annotation SummarizationSetBy = Automatic

	column cancellation_rate
		dataType: double
		summarizeBy: sum
		sourceColumn: cancellation_rate
		annotation SummarizationSetBy = Automatic

	column on_time_rate
		dataType: double
		summarizeBy: sum
		sourceColumn: on_time_rate
		annotation SummarizationSetBy = Automatic

	column sla_breach_rate
		dataType: double
		summarizeBy: sum
		sourceColumn: sla_breach_rate
		annotation SummarizationSetBy = Automatic

	column avg_delivery_days
		dataType: double
		summarizeBy: sum
		sourceColumn: avg_delivery_days
		annotation SummarizationSetBy = Automatic

	column cost_per_delivered_order_inr
		dataType: double
		summarizeBy: sum
		sourceColumn: cost_per_delivered_order_inr
		annotation SummarizationSetBy = Automatic

	partition default = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:/Users/Asus/OneDrive/Documents/2nd data analayst project/data/processed/vendor_performance.csv"),[Delimiter=",", Columns=8, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"vendor", type text}, {"total_orders", Int64.Type}, {"delivered_orders", Int64.Type}, {"cancellation_rate", type number}, {"on_time_rate", type number}, {"sla_breach_rate", type number}, {"avg_delivery_days", type number}, {"cost_per_delivered_order_inr", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	measure 'Total Vendor Orders' = SUM('Vendor Performance'[total_orders])
		formatString: 0

	measure 'Vendor On-Time Rate' = AVERAGE('Vendor Performance'[on_time_rate])
		formatString: 0.0%

	measure 'Vendor SLA Breach Rate' = AVERAGE('Vendor Performance'[sla_breach_rate])
		formatString: 0.0%

	measure 'Vendor Avg Delivery Days' = AVERAGE('Vendor Performance'[avg_delivery_days])
		formatString: 0.0
